# Generated by Django 4.0.6 on 2022-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='room',
            name='economy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='royals',
            field=models.BooleanField(default=False),
        ),
    ]
