# Generated by Django 4.0.6 on 2022-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_room_business_room_description_room_economy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='business',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='economy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='family',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='royals',
            field=models.BooleanField(),
        ),
    ]
