# Generated by Django 4.0.6 on 2022-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_room_business_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gallery1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='gallery2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='gallery3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='gallery4',
            field=models.BooleanField(default=False),
        ),
    ]
