# Generated by Django 4.0.6 on 2022-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room_gallery1_room_gallery2_room_gallery3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gallery1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='gallery2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='gallery3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='gallery4',
            field=models.BooleanField(),
        ),
    ]
