# Generated by Django 4.0.6 on 2022-07-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gallery_remove_room_gallery1_remove_room_gallery2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
