# Generated by Django 4.0.6 on 2022-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gallery', models.ImageField(default='gallery.jpg', upload_to='gallery')),
                ('economy', models.BooleanField()),
                ('business', models.BooleanField()),
                ('family', models.BooleanField()),
                ('royals', models.BooleanField()),
            ],
        ),
    ]
