# Generated by Django 4.0.6 on 2022-07-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='business',
            new_name='slide1',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='economy',
            new_name='slide2',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='family',
            new_name='slide3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='royals',
        ),
    ]
