# Generated by Django 4.0.6 on 2022-07-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
