# Generated by Django 4.0.6 on 2022-07-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
