# Generated by Django 4.0.6 on 2022-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_num',
            field=models.CharField(default='a', max_length=5),
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.CharField(default='a', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_days',
            field=models.IntegerField(),
        ),
    ]
