# Generated by Django 4.0.6 on 2022-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_booking_book_no_remove_booking_no_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_num',
            field=models.CharField(max_length=5),
        ),
    ]
