# Generated by Django 4.0.6 on 2022-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_booking_room_alter_booking_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
