# Generated by Django 4.0.6 on 2022-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_booking_no_days_alter_booking_price_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_c',
            field=models.TextField(default='a'),
        ),
    ]
