# Generated by Django 4.0.6 on 2022-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_category_slug_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
    ]
